name: "Request PR Review"
description: "Request pull request review to reviewers periodically"
inputs:
  token:
    description: "github token"
    required: true
  # kakaobotToken:
  #   description: "kakao bot token for messaging"
  #   required: true
  repoUrl:
    description: "repository url where action runs"
    required: true
runs:
  using: node12
  main: request-pr-review/test.js
